version: "3"
services:
  mysql:
    #image: mysql:5.7.36
    #指定容器名称
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: asterisk-mysql
    #restart: always
    #network_mode: "host"
    #指定服务运行的端口
    ports :
      - "3336:3306"
    #指定容器的环境变量
    environment:
      #数据库密码
      - MYSQL_ROOT_PASSWORD=root
      #允许多IP连接数据库
      - MYSQL_ROOT_HOST=%
    #挂载数据卷
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
#      - ./mysql/datad:/var/run/mysqld
      - ./mysql/datal:/var/log/mysql
  asterisk:
    #自己构建的镜像，当前路径Dockerfile
    build:
      context: .
      dockerfile: Dockerfile-asterisk
    container_name: asterisk-sip
    #restart: always
    #指定服务运行的端口
    network_mode: "host"
    #ports:
    #  - "5060:5060/udp"
    #挂载数据卷
    volumes:
      - ./audio_program:/home/dev/program
      - ./asterisk/conf/asterisk:/etc/asterisk
      - ./asterisk/opt/asterisk-18:/opt/asterisk-18
      - ./asterisk/etc:/etc

    #依赖的服务
    command: bash -c "
        asterisk -vvvc
      "
    depends_on:
      - mysql
    
  java-app:
    build:
      #dockerfile存放路径
      context: .
      dockerfile: Dockerfile-app
    #network_mode: "host"
    ports:
      - "8890:8090"

    volumes:
      - ./audio_program:/home/dev/program

    depends_on:
      - asterisk
